[package]
name = "mail-sender"
version = "0.1.0"
edition = "2021"

[dependencies]
lettre = "0.11.14"
liquid = "0.26.9"
rocket = "0.5.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tokio = "1.43.0"
